language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
deploy:
  provider: heroku
  skip_cleanup: true
  app:
    master: idividends-data
  on:
    repo: sergiotorreslozano/idividends-data
  api_key:
    secure: NG2i7okcjQRG8Q68m2EwvDlTcFhetP1h0yCCSThg2iwsW+nJS67WvI7NcprCyNw4ZH3RFmBfIDEj7A7G/2KI+FRJBTK7nVG43tdjG5vls1Zm75q0o9Q2kJCDVvNFRk0QLzrpoz3Tdhf3lrISQoS7DZ2U/d5vdjyso18jiF34a66JbI2CeIewutc0RSz55hjHeTEGDlC0DkdDfSrYWLX3MnxThTTp2gh0uZgl5+SymRp+opVzYMC7ZkFRz87faoRg6mfXkSGCQY7bf3o9l/H50J+DBhqOzzjQFOp6MqbKg9H5JLPEBUbjg9eaTlOAWnUppQ/AZPiyDDD8SIH9nBzXgivsz+ojdi/vPI1C5tIaTgzDHTqd29uvVfwG1snCErRGzdxMA0pJaBQFsDo1D+bss80nADRNvEn02kzUgfBlMJqJ8yZPDw3gXDNB7M/+inUXm2wT9LAGCN9uHA1WQDvZOI5KQsu1Q1Fat0ZZn/7RHdgYLoE0fF7idha7VbyDis9+OhO/BzWi/rpenoVqZHyS03DRleHhFujEUSCmaCpwKNhPNLkREa8Kww2g3QjynoLyzJomCkVnkrPyksf8I9qXTMltpYdYJukmCkxwzVof+XCw7PF1WGjwTwwPIj/MPAJfZT/ky05wK6y8IPiDh1aFx0GqMU38EQSmqNyKo/M1xMc=
script: mvn test -B -Dspring.profiles.active=test
