language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
deploy:
  provider: heroku
  skip_cleanup: true
  app:
    master: idividends-data
  on:
    repo: sergiotorreslozano/idividends-data
  api_key:
    secure: RavyoAnXJxlsv5+F0n8VLS7s1lRmEOYdSzHH3MbYI9QDpGpNzY6FtwSL2mdkNWFoNPUh0lFxWEbjWTYsLB3nblbGuCZh17vcDp8/r9Gwfd3xDCB6UOaHeRRkVUtvPeu7uWbYUZm2haAmJyBFG3OcgSIWxxe7Z39vTzsUQeEuAimOL/NAOnNyB6SCv7Vkwq2QTxJAMGmSk+gb6VXCnS0NbhThm5VW7kGPCU8tPytk/3GYDAz10DWMUwI07a43KuhyGC63pIMM/Y2vLtA0ndG/OT5wshQnkT4oDASH3+YujltH/Rd5Bh2bwqAeINL7nT1Nmrts5Dw7CWKeAUgrmL+trHzsYscZwaRXC3I6NjMQH3vBRBHwkN9Wnc69leccs9KJFq/LbtD1QGKPRT8OstpvQ+4WxYU5O7Ev7SN9JtlsiC29XPFkDheVdxeKNVulwLgW0hhuBTQ12RwOV/CU0U/+GzNtU9lY9Cb1Qto2KwToUnFXVwfbqBg87qjmoV0h0w5GhrUFOZHOZ2mjCP1+M+tOm0Yv7LPd6aW7ZCdC12AqYui3qwQc1kYePP4U981OZHnh4LoSNm+G6Mq2zEOF7AOdtW2cDl0K3Z+6q/DnZeCTOknJhmGRyf5aklnpW8nH46SM1d2zrbWqh4ZtAfFoqKsbntyCrlsRqBnGpY/BneYYu0E=
script: mvn test -B -Dspring.profiles.active=test
